---
- name: fqdn | Configure Debian
  ansible.builtin.import_tasks:
    file: debian.yml
  when: ansible_os_family == 'Debian'

- name: fqdn | Configure Redhat
  ansible.builtin.import_tasks:
    file: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: fqdn | Configure Linux
  ansible.builtin.import_tasks:
    file: linux.yml
  when: ansible_system in  [ 'Linux' ]

- name: fqdn | Configure Windows
  ansible.builtin.import_tasks:
    file: windows.yml
  when: ansible_system in  [ 'Win32NT' ]
