---
- name: Redhat | Install libselinux-python on el7
  yum:
    name: libselinux-python
  when: (ansible_facts['distribution'] == "CentOS"
    and ansible_facts['distribution_major_version'] == "7")

- name: Redhat | Install libselinux-python on el8
  yum:
    name: python3-libselinux
  when: (ansible_facts['distribution'] == "CentOS"
   or "Rocky" and ansible_facts['distribution_major_version'] >= "8")

- name: Redhat | Update sysconfig
  ansible.builtin.lineinfile:
    path: /etc/sysconfig/network
    regexp: "HOSTNAME="
    line: "HOSTNAME={{ fqdn }}" 
    create: yes
