---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: almalinux-9
    image: almalinux:9
    pre_build_image: true
    command: /usr/sbin/init
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
