---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos-9
    image: quay.io/centos/centos
    pre_build_image: true
    command: /usr/sbin/init
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
